language: python
python:
  - "3.9-dev"
  - "3.8"
  - "3.7"
matrix:
  allow_failures:
    - python: "3.9-dev"
before_install:
  - pip install -U pip setuptools
install: pip install .
script:
  - pip install -r script/testing/requirements.txt
  - ./run-tests
  # Deliberately after running the real tests so that we can't accidentally
  # depend on it
  - pip install -r script/linting/requirements.txt
  - script/linting/lint
  - pip install -r script/typing/requirements.txt
  - script/typing/check
